apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: rekrutteringstreff-bruker
    namespace: toi
    labels:
        team: toi
spec:
    groups:
        - name: rekrutteringstreff-bruker
          rules:
              - alert: rekrutteringstreff-bruker
                expr: kube_deployment_status_replicas_available{deployment="rekrutteringstreff-bruker"} == 0
                for: 1s
                annotations:
                    summary: Appen er nede
                    action: "https://logs.az.nav.no/goto/b2b9fb41b1263789068a2e7ebd12946e?security_tenant=navlogs"
                labels:
                    namespace: toi
                    severity: critical

              - alert: rekrutteringstreff-bruker
                expr: sum(increase(log_messages_errors{app="rekrutteringstreff-bruker", level="Error"}[10m])) > 0
                for: 1s
                annotations:
                    summary: Appen har logget en error
                    action: "https://logs.az.nav.no/goto/b2b9fb41b1263789068a2e7ebd12946e?security_tenant=navlogs"
                labels:
                    namespace: toi
                    severity: critical

              - alert: rekrutteringstreff-bruker
                expr: sum(increase(log_messages_errors{app="rekrutteringstreff-bruker", level="Warning"}[10m])) > 3
                for: 1s
                annotations:
                    summary: Økning i warnings
                    action: "https://logs.az.nav.no/goto/b2b9fb41b1263789068a2e7ebd12946e?security_tenant=navlogs"
                labels:
                    namespace: toi
                    severity: warning
