apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: toi
  name: rekrutteringstreff-bruker
  namespace: toi
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  replicas:
    max: 2
    min: 1
  image: {{ image }}
  ingresses:
    - {{ NEXT_PUBLIC_BASE_URL }}
  port: 3000
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  tokenx:
    enabled: true
  accessPolicy:
     outbound:
        rules:
          - application: rekrutteringstreff-minside-api     
  env:
    - name: NEXT_PUBLIC_BASE_URL
      value: {{ NEXT_PUBLIC_BASE_URL }}
    - name: REKRUTTERINGSTREFF_MINSIDE_API
      value: http://rekrutteringstreff-minside-api

