apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: toi
  name: rekrutteringstreff-bruker
  namespace: toi
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
  replicas:
    max: 2
    min: 1
  image: {{ image }}
  ingresses:
    - {{ NEXT_PUBLIC_BASE_URL }}
  port: 3000
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  accessPolicy:
     outbound:
        rules:
          - application: rekrutteringstreff-minside-api
          - application: nav-dekoratoren
            namespace: personbruker
  env:
    - name: NEXT_PUBLIC_BASE_URL
      value: {{ NEXT_PUBLIC_BASE_URL }}
    - name: REKRUTTERINGSTREFF_MINSIDE_API
      value: http://rekrutteringstreff-minside-api
    - name: LOGIN_URL
      value: {{ login_url }}
