name: Dependabot PNPM Support

on:
  pull_request:
    branches: [main, master]
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update pnpm lockfile
          file_pattern: pnpm-lock.yaml